document.write("<table cellpadding=\"0\" cellspacing=\"0\" class=\"table-left-border\">");
        document.write("<tr>");
          document.write("<td class=\"list-header-td\">相关文档管理（点鼠标右键“目标另存为”可下载保存相关文档）〖<a href=\"#\" onclick=\"fileupload();\"><b>点这里上传新的文档</b></a>〗</td>");
        document.write("</tr>");
        document.write("<tr>");
          document.write("<td>");
		  document.write("<table cellpadding=\"0\" cellspacing=\"0\" class=\"table-width\">");
            document.write("<tr>");
              document.write("<td class=\"list-top-title\">&nbsp;</td>");
			  document.write("<td class=\"list-top-title\">文档名称</td>");
              document.write("<td class=\"list-top-title\">文档类型</td>");
              document.write("<td class=\"list-top-title\">描述</td>");
              document.write("<td class=\"list-top-title\">文档创建人</td>");			
              document.write("<td class=\"list-top-title\">文档创建日期</td>");
              document.write("<td class=\"list-top-title\">操作</td>");
			  document.write("</tr>");
            document.write("<tr>");
              document.write("<td class=\"list-center-title\">1</td>");
              document.write("<td class=\"info-left-td\">");
			  document.write("<a href=\"#\">某某X某X某某某文档</a>");
			  document.write("</td>");
              document.write("<td class=\"info-left-td\">&nbsp;</td>");
              document.write("<td class=\"info-left-td\">&nbsp;</td>");
              document.write("<td class=\"info-left-td\">&nbsp;</td>");
              document.write("<td class=\"info-left-td\">&nbsp;</td>");
              document.write("<td class=\"list-caozuo-td\"><a href=\"#\" onclick=\"fileupload();\">修改</a>｜<a href=\"#\">删除</a></td>");
			  document.write("</tr>");
		    document.write("</table>");
		  document.write("</td>");
        document.write("</tr>");
      document.write("</table>");
