var title="项目可研";
var t,itemid;
t=outlookbar.addtitle('项目可研')
itemid=outlookbar.additem('可研报告提交',t,'analyze/project.analyze.reporting.htm','')
outlookbar.additem('可研会审纪要编制',t,'analyze/project.analyze.confirm.htm','')
outlookbar.additem('查看可研报告',t,'analyze/project.analyze.preview.htm','')
outlookbar.additem('可研批复编制',t,'analyze/project.analyze.ratify-edit.htm','')
outlookbar.additem('集团可研批复编制',t,'analyze/project.analyze.gorup.ratify-edit.htm','')
outlookbar.additem('可研批复查看',t,'analyze/project.analyze.ratify-view.htm','')
outlookbar.additem('集团可研批复查看',t,'analyze/project.analyze.group.ratify-view.htm','')

t=outlookbar.addtitle('工程设计')
itemid=outlookbar.additem('设计委托',t,'design/project.design.entrust.htm','')
outlookbar.additem('初步设计会审',t,'design/project.design.confirm.htm','')
outlookbar.additem('初步设计批复',t,'design/project.design.approval.htm','')
outlookbar.additem('施工图设计会审',t,'design/project.design.pic.confirm.htm','')
outlookbar.additem('施工图设计批复',t,'design/project.design.pic.approval.htm','')
outlookbar.additem('施工图设计交底',t,'design/project.design.pic.disclose.htm','')
outlookbar.additem('初步设计变更',t,'design/project.design.change.htm','')
outlookbar.additem('施工图设计变更',t,'design/project.design.pic.change.htm','')

t=outlookbar.addtitle('工程监理')
itemid=outlookbar.additem('监理委托',t,'inspect/project.inspect.entrust.htm','')
outlookbar.additem('监理报备',t,'inspect/project.inspect.archive.htm','')
outlookbar.additem('监理总结报告',t,'inspect/project.inspect.summarize.htm','')

t=outlookbar.addtitle('工程实施')
itemid=outlookbar.additem('质检申报信息',t,'actulize/project.actulize.quality.htm','')
itemid=outlookbar.additem('项目开工记录',t,'actulize/project.actulize.start.htm','')
itemid=outlookbar.additem('项目进度查看',t,'actulize/project.actulize.schedule.htm','')
itemid=outlookbar.additem('形象进度表编制',t,'actulize/project.actulize.cyclecost.htm','')
//itemid=outlookbar.additem('成本投资情况',t,'actulize/project.actulize.investcost.htm','')
itemid=outlookbar.additem('项目完工记录',t,'actulize/project.actulize.finish.htm','')

t=outlookbar.addtitle('项目验收')
itemid=outlookbar.additem('初验申请记录',t,'check/project.check.earlyapply.htm','')
outlookbar.additem('初验会审记录',t,'check/project.check.earlyconfirm.htm','')
outlookbar.additem('初验批复记录',t,'check/project.check.earlyapproval.htm','')
outlookbar.additem('资产暂固',t,'check/project.check.assetfixup.htm','')
outlookbar.additem('施工审计记录',t,'check/project.check.auditinfo.htm','')
outlookbar.additem('初验移交记录',t,'check/project.check.handover.htm','')
outlookbar.additem('终验申请记录',t,'check/project.check.endapply.htm','')
outlookbar.additem('终验会审记录',t,'check/project.check.endconfirm.htm','')
outlookbar.additem('终验批复记录',t,'check/project.check.endapproval.htm','')
outlookbar.additem('工程决算申请',t,'check/project.check.budgetapply.htm','')
outlookbar.additem('工程决算转固',t,'check/project.check.budgetfixup.htm','')